<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" />
  <link href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" rel="stylesheet">
  <link rel="stylesheet" href="../assets/css/style.css">
  <title>Vendor Table</title>
</head>
<body>
<?php include('../navbar.php'); ?>
<div class="container mt-7">
  <div class="dataTable_card card">
    <div class="card-header d-flex justify-content-between align-items-center">
      <h5 class="mb-0 table-title">Vendor Table</h5>
      <a href="javascript:void(0);" class="add_button" onclick="addVendor()">
        <strong class="add_button_plus">+</strong> Add Vendor
      </a>
    </div>

    <div class="table-responsive mt-3 p-4">
      <table id="vendorTable" class="display table table-striped" style="width:100%">
        <thead>
          <tr>
            <th>S.no</th>
            <th>Vendor Name</th>
            <th>Phone Number</th>
            <th>Email</th>
            <th>Vendor Type</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <!-- Rows will be dynamically generated by DataTables -->
        </tbody>
      </table>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="viewModal" tabindex="-1" aria-labelledby="viewModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="viewModalLabel">Vendor Details</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <ul id="vendorDetails" class="list-group">
          <!-- Vendor details will be dynamically inserted here -->
        </ul>
      </div>
    </div>
  </div>
</div>

<!-- JavaScript -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>

<script>
  function addVendor() {
    window.location.href = "vendor_form.php";
  }

  $(document).ready(function () {
    // Initialize DataTable
    const vendorTable = $('#vendorTable').DataTable({
      processing: true,
      serverSide: true,
      ajax: {
        url: 'fetch_vendors.php', // Server-side script to fetch data
        type: 'POST',
        data: function (d) {
          d.search_value = d.search.value; // Pass search value from DataTables built-in search
        }
      },
      columns: [
        { data: null, render: (data, type, row, meta) => meta.row + 1 }, // Serial number
        { data: 'vendor_name' },
        { data: 'phone_number' },
        { data: 'email' },
        { data: 'vendor_type' },
        {
          data: 'id',
          render: (data) => `
            <i class="fas fa-eye icon-black" onclick="viewVendor(${data})" title="View"></i>
            <i class="fas fa-edit ms-2 icon-black" onclick="editVendor(${data})" title="Edit"></i>
            <i class="fas fa-trash ms-2 icon-black" onclick="deleteVendor(${data})" title="Delete"></i>
          `
        },
      ],
      paging: true, // Enable pagination
      searching: true, // Enable global search
      ordering: true, // Enable column ordering
      lengthMenu: [5, 10, 20, 50], // Rows per page options
      pageLength: 5, // Default rows per page
      language: {
        search: "Search Vendors:", // Customize the search label
      },
    });

    window.viewVendor = function (id) {
  fetch(`fetch_vendor_details.php?id=${id}`)
    .then((response) => {
      if (!response.ok) {
        throw new Error('Network response was not ok');
      }
      return response.json();
    })
    .then((data) => {
      if (data.error) {
        alert(data.error);  // Show error if the vendor details cannot be fetched
      } else {
        const detailsList = Object.entries(data)
          .map(([key, value]) => `<li class="list-group-item"><strong>${key}:</strong> ${value || "N/A"}</li>`)
          .join("");
        document.getElementById("vendorDetails").innerHTML = detailsList;
        const modal = new bootstrap.Modal(document.getElementById("viewModal"));
        modal.show();
      }
    })
    .catch((error) => {
      alert("Error fetching vendor details: " + error.message);
      console.error(error);
    });
};

    // Edit Vendor
    window.editVendor = function (id) {
      window.location.href = `update_vendor.php?id=${id}`;
    };

    window.deleteVendor = function (id) {
    if (confirm(`Are you sure you want to delete vendor ID: ${id}?`)) {
        $.ajax({
            url: `delete_vendor.php`,
            type: 'POST',
            data: { id: id }, // Send 'id' as POST data
            success: function (response) {
                const result = JSON.parse(response);
                if (result.success) {
                    alert(result.message);
                    $('#vendorTable').DataTable().ajax.reload(); // Reload table data
                } else {
                    alert(result.message);
                }
            },
            error: function () {
                alert('Error deleting vendor.');
            },
        });
    }
};

  });
</script>
</body>
</html>
